apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-example
  namespace: dev-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-example
  template:
    metadata:
      labels:
        app: nextjs-example
    spec:
      containers:
        - name: nextjs-example
          image: asia-east1-docker.pkg.dev/ecom-lab/gcf-artifacts/dev/nextjs-example:0.0.0
          ports:
            - port: 3000
            - containerPort: 3000
      imagePullSecrets:
        - name: gcp-artifact-registry
