apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-env

resources:
- deployment.yaml
- ./../../base
images:
- name: asia-east1-docker.pkg.dev/direct-mission-449804-a7/trietmapdit/dev/nextjs-example
  newTag: e02d77afc6f0bc87b5ed582507200cde01466237
